import Mathlib

open Filter Set TopologicalSpace
open scoped Topology

def is_topology (X : Type*) (T : Set (Set X)) :=
  univ ∈ T ∧
  (∀ s t, s ∈ T → t ∈ T → s ∩ t ∈ T) ∧
  (∀s, (∀t ∈ s, t ∈ T) → sUnion s ∈ T)

/-Informal Statement

Show that if $\mathcal{A}$ is a basis for a topology on $X$, then the topology generated by $\mathcal{A}$ equals the intersection of all topologies on $X$ that contain $\mathcal{A}$.
-/

theorem Munkres_exercise_13_5a {X : Type*}
  (A : Set (Set X))
  (hcover : ∀ x : X, ∃ B ∈ A, x ∈ B)
  (hrefine : ∀ B₁ ∈ A, ∀ B₂ ∈ A, ∀ x ∈ B₁ ∩ B₂, ∃ B₃ ∈ A, x ∈ B₃ ∧ B₃ ⊆ B₁ ∩ B₂) :
  {U : Set X | @IsOpen X (generateFrom A) U}
    =
  sInter {T : Set (Set X) | is_topology X T ∧ A ⊆ T} := by
  sorry
