import Mathlib

open Fintype Subgroup Set Polynomial Ideal
open scoped BigOperators



/-Informal Statement

Prove that if $H$ is a subgroup of $G$ then $H$ is generated by the set $H-\{1\}$.
-/

theorem Dummit_Foote_exercise_2_4_4 {G : Type*} [Group G] (H : Subgroup G) :
    Subgroup.closure ((H : Set G) \ {1}) = H := by
  sorry
