import Mathlib

open Fintype Subgroup Set Polynomial Ideal
open scoped BigOperators
noncomputable section

/-Informal Statement

Prove that if $H$ is a subgroup of $G$ then $H$ is generated by the set $H-\{1\}$.
-/

theorem Dummit_Foote_exercise_2_4_4 {G : Type*} [Group G] (H : Subgroup G) :
  closure ((H : Set G) \ {1}) = ⊤ := by
  sorry
